[package]
name = "simple"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow = "1.0.97"
styled_text.workspace = true

[lints]
workspace = true
